image: node:20

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

build:
  stage: build
  script:
    - npm run build:pages
  artifacts:
    paths:
      - dist/monchito-game-library
    expire_in: 1 hour

pages:
  stage: deploy
  script:
    - mv dist/monchito-game-library public
  artifacts:
    paths:
      - public
  only:
    - main
