#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

NODE_VERSION=$(cat "$(dirname "$0")/../.nvmrc" 2>/dev/null || echo "")
[ -n "$NODE_VERSION" ] && export PATH="$HOME/.nvm/versions/node/v${NODE_VERSION}/bin:$PATH"

npx lint-staged
